[package]
name = "quaza-shooter"
version = "0.1.0"
edition = "2021"

[dependencies]
starknet = "0.13.0"
tokio = { version = "1.43", features = ["full"] }
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"